Add "new" constructor estimate gas usage
Brushfam/typechain-polkadot pull request #98
Opened 2023-06-07 20:04 UTC by varex83

Closes #45

2023-06-07 20:06 UTC, Artemka374 approved these changes

2023-06-07 20:06 UTC, Artemka374 approved these changes

2023-06-07 20:08 UTC, Artemka374 requested changes
i don't like it

2023-06-07 20:09 UTC, Artemka374 approved these changes

2023-06-07 20:09 UTC, merged

2023-06-21 09:09 UTC, deuszx commented on packages/typechain-types/src/tx.ts
> +	};
Even though we estimate here, why do I still need to estimate manually when calling contract's methods? i.e. I need to first do `<contract>.query.<method>(...)` , record the `gasRequired` and then use that as the limit in the subsequent `<contract>.tx.<method>`. Without it the `tx` call fails. cc @varex83